version: 2
updates:
- package-ecosystem: nuget
  directory: "/HyTekLanguageApplication"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: HtmlAgilityPack
    versions:
    - 1.11.30
    - 1.11.31
    - 1.11.32
  - dependency-name: ServiceStack.OrmLite
    versions:
    - 5.10.4
  - dependency-name: ServiceStack.OrmLite.SqlServer
    versions:
    - 5.10.4
  - dependency-name: ServiceStack.Common
    versions:
    - 5.10.4
  - dependency-name: ServiceStack.Client
    versions:
    - 5.10.4
  - dependency-name: ServiceStack.Text
    versions:
    - 5.10.4
  - dependency-name: ServiceStack.Interfaces
    versions:
    - 5.10.4
  - dependency-name: Antlr4.Runtime.Standard
    versions:
    - 4.9.1
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
